language: go
go_import_path: github.com/renaynay/go-canonical-serialization
sudo: false
env:
  - GOPATH=/home/travis/gopath
#  - GO111MODULE=on

os: linux
dist: xenial
sudo: required
go: 1.12.x

before_install:
  - go get -u golang.org/x/lint/golint

script:
  - golint ./...
  - go get ./...
  - go test ./...
  - go test -bench=./...
